[package]
name = "dataversion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-varint = "0.1.0-dev.1"
thiserror = "1"

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1"
pot = "0.1.0-alpha.3"
thiserror = "1"
anyhow = "1"
