[package]
name = "transmog"
version = "0.1.0-dev.1"
edition = "2021"
repository = "https://github.com/khonsulabs/transmog"
license = "MIT OR Apache-2.0"
keywords = ["serialization"]
categories = ["encoding"]
readme = "../README.md"

[features]
default = []
test-util = []
