[package]
name = "transmog-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
transmog = { path = "../transmog" }
futures-core = { version = "0.3" }
futures-sink = { version = "0.3" }
tokio = { version = "1.0", features = ["net"] }
bytes = { version = "1.0" }
ordered-varint = "0.1.0-dev.1"

[dev-dependencies]
thiserror = "1"
anyhow = "1"
futures = "0.3"
tokio = { version = "1.0", features = ["full"] }
transmog-bincode = { path = "../transmog-bincode" }
transmog-pot = { path = "../transmog-pot" }
# serde = { version = "1"}
