[package]
name = "transmog-pot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pot = { version = "1.0.0-rc.1" }
transmog = { path = "../transmog" }
serde = "1"
